/**
 * job-portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: local
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ApplicationUpdateDto { 
    state?: ApplicationUpdateDto.StateEnum;
}
export namespace ApplicationUpdateDto {
    export type StateEnum = 'OPEN' | 'SEEN' | 'APPROVED' | 'DECLINED' | 'CLOSED';
    export const StateEnum = {
        OPEN: 'OPEN' as StateEnum,
        SEEN: 'SEEN' as StateEnum,
        APPROVED: 'APPROVED' as StateEnum,
        DECLINED: 'DECLINED' as StateEnum,
        CLOSED: 'CLOSED' as StateEnum
    };
}