server:
  port: ${PORT:8080}
  servlet:
    encoding:
      force: true

spring:
  application:
    name: jobportal
  liquibase:
    enabled: true
    contexts: default, data
    change-log: classpath:db/changelog/master.xml
    drop-first: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      'hibernate.cache.use_second_level_cache': true
      'hibernate.cache.region.factory_class': org.hibernate.cache.jcache.JCacheRegionFactory
      'hibernate.cache.use_query_cache': true
      'hibernate.search.backend.analysis.configurer': muni.fi.cz.jobportal.configuration.search.LuceneConfiguration
      'hibernate.search.backend.directory.root': ./tmp/index
  datasource:
    url: jdbc:postgresql://localhost:5432/jobportal
    username: jobportal
    password: jobportal
  servlet:
    multipart:
      enabled: true
      location: ./tmp/img
      max-file-size: 128KB
      max-request-size: 128KB
  mail:
    host: ${EMAIL_STMP_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_NOTIFICATION_APP_USERNAME}
    password: ${EMAIL_NOTIFICATION_APP_PASSWORD}
    properties:
      mail:
        smtp.auth: ${NOTIFICATIONS_ENABLED:false}
        smtp.starttls.enable: ${NOTIFICATIONS_ENABLED:false}
springdoc:
  packages-to-scan:
    - muni.fi.cz.jobportal.resource
  api-docs:
    resolve-schema-properties: true
  writer-with-order-by-keys: true
  default-produces-media-type: application/json

job-portal:
  key-store:
    key-store-password: ${KEY_STORE_PASSWORD:KKLdv39i3EW}
    key-pair-name: ${KEY_PAIR_NAME:keypair}
    key-pair-password: ${KEY_PAIR_PASSWORD:SAui78gew8Y}
    location: ${KEY_STORE_LOCATION:classpath:/keypair}
    kid: ${KEY_STORE_KID:kid}
  access-token:
    duration: ${ACCESS_TOKEN_DURATION:1H}
  refresh-token:
    duration: ${REFRESH_TOKEN_DURATION:1D}
  notifications:
    enabled: ${NOTIFICATIONS_ENABLED:false}
  base-uri: ${BASE_URI:http://localhost:8080}
