/**
 * job-portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: local
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApplicantDetailDto } from './applicantDetailDto';
import { JobPositionDetailDto } from './jobPositionDetailDto';

export interface ApplicationDetailDto { 
    applicant?: ApplicantDetailDto;
    date?: Date;
    id?: string;
    jobPosition?: JobPositionDetailDto;
    state?: ApplicationDetailDto.StateEnum;
}
export namespace ApplicationDetailDto {
    export type StateEnum = 'OPEN' | 'SEEN' | 'APPROVED' | 'DECLINED' | 'CLOSED';
    export const StateEnum = {
        OPEN: 'OPEN' as StateEnum,
        SEEN: 'SEEN' as StateEnum,
        APPROVED: 'APPROVED' as StateEnum,
        DECLINED: 'DECLINED' as StateEnum,
        CLOSED: 'CLOSED' as StateEnum
    };
}