/**
 * job-portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: local
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RepeatPasswordDto } from './repeatPasswordDto';

export interface UserUpdateDto { 
    oldPassword?: string;
    password?: RepeatPasswordDto;
}