export * from './applicant.service';
import { ApplicantService } from './applicant.service';
export * from './application.service';
import { ApplicationService } from './application.service';
export * from './authorization.service';
import { AuthorizationService } from './authorization.service';
export * from './company.service';
import { CompanyService } from './company.service';
export * from './jobPosition.service';
import { JobPositionService } from './jobPosition.service';
export * from './jobPositionCategory.service';
import { JobPositionCategoryService } from './jobPositionCategory.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [ApplicantService, ApplicationService, AuthorizationService, CompanyService, JobPositionService, JobPositionCategoryService, UserService];
