# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and test application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      run_docker:
        description: 'Run Docker job'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7
        options: --privileged  # Ensures that Docker has the necessary permissions
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests=false -DskipITs=false

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master' && github.event.inputs.run_docker == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        if: github.ref == 'refs/heads/master'
        run: DOCKER_BUILDKIT=1 docker build . --file Dockerfile --tag ${{ github.event.repository.name }}:${{ github.sha }}

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/master'
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to registry
        if: github.ref == 'refs/heads/master'
        run: docker push ${{ github.event.repository.name }}:${{ github.sha }}
